arguments:
  format: json
git_services:
- host: github.com
  repos:
  - konflux-ci/release-service
  - konflux-ci/release-service-utils
  - konflux-ci/internal-services
  - konflux-ci/release-service-catalog
  - konflux-ci/e2e-tests
  - konflux-ci/build-definitions
  - konflux-ci/build-trusted-artifacts
  - konflux-ci/docs
  - redhat-appstudio/infra-deployments
  token: "${GITHUB_TOKEN}"
  type: github
