name: Publish

on:
  push:
    branches:
      - main
  schedule:
    # Every 30 minutes, Monday through Friday
    - cron: '*/30 * * * 1-5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Process config
        env:
          GITHUB_TOKEN: ${{ secrets.KRS_AUTOMATION_KEY }}
        run: |-
          set -euo pipefail
          < ./config.yaml envsubst > config-with-token.yaml
          cat config-with-token.yaml

      - name: Run review-rot
        uses: lcarva/review-rot-action/run@cb3c7455d9489ac76d1366076d19d1b91e9384a6 # main
        with:
          config: config-with-token.yaml
          output: output.json

      - name: Process data
        run: |-
          set -euo pipefail
          echo '=== START OF FULL DATA ==='
          cat output.json
          echo '==== END OF FULL DATA ===='

          mkdir web

          < output.json ./filter-data.sh > web/data.json
          echo '=== START OF FILTERED DATA ==='
          cat web/data.json
          echo '==== END OF FILTERED DATA ===='

      - name: Fetch review-rot web
        uses: lcarva/review-rot-action/web@cb3c7455d9489ac76d1366076d19d1b91e9384a6 # main
        with:
          output: web

      - name: Configure pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: web

      - name: Deploy pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deployment
